/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Default;
import Default.Candidate;
import Default.AutocompleteProvider;
/**
 *
 * @author chr
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
    }
  
    public AutocompleteProvider trie = new AutocompleteProvider();
    
    public String docuementInput;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DocumentArea = new javax.swing.JTextArea();
        UserInput = new javax.swing.JTextField();
        SuggestionsLabel = new javax.swing.JLabel();
        SuggestionsOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DocumentArea.setColumns(20);
        DocumentArea.setLineWrap(true);
        DocumentArea.setRows(5);
        DocumentArea.setText("The third thing that I need to tell you is that this thing does not think thoroughly.");
        DocumentArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DocumentAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DocumentAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(DocumentArea);

        UserInput.setText("thi");
        UserInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserInputKeyReleased(evt);
            }
        });

        SuggestionsLabel.setText("Suggestions:");

        SuggestionsOutput.setText("thing (2), this (1), third(1), think (1)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SuggestionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SuggestionsOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuggestionsLabel)
                    .addComponent(SuggestionsOutput))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DocumentAreaKeyPressed
        trie.train(DocumentArea.getText());
        SuggestionsOutput.setText(trie.PrintCandidates(trie.getWords(UserInput.getText().toLowerCase())));
    }//GEN-LAST:event_DocumentAreaKeyPressed

    private void UserInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserInputKeyReleased
        trie.train(DocumentArea.getText());
        SuggestionsOutput.setText(trie.PrintCandidates(trie.getWords(UserInput.getText().toLowerCase())));
    }//GEN-LAST:event_UserInputKeyReleased

    private void DocumentAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DocumentAreaKeyReleased
        trie.train(DocumentArea.getText());
        SuggestionsOutput.setText(trie.PrintCandidates(trie.getWords(UserInput.getText().toLowerCase())));
    }//GEN-LAST:event_DocumentAreaKeyReleased

    private void UserInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserInputKeyPressed
        trie.train(DocumentArea.getText());
        SuggestionsOutput.setText(trie.PrintCandidates(trie.getWords(UserInput.getText().toLowerCase())));
    }//GEN-LAST:event_UserInputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DocumentArea;
    private javax.swing.JLabel SuggestionsLabel;
    private javax.swing.JLabel SuggestionsOutput;
    private javax.swing.JTextField UserInput;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
